#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "example"
name = "Example app"
description.en = "Explain in *a few (10~15) words* the purpose of the app or what it actually does (it is meant to give a rough idea to users browsing a catalog of 100+ apps)"
description.fr = "Expliquez en *quelques* (10~15) mots l'utilité de l'app ou ce qu'elle fait (l'objectif est de donner une idée grossière pour des utilisateurs qui naviguent dans un catalogue de 100+ apps)"

version = "1.3.0~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "AGPL-3.0"
website = "https://ovumcy.com/"
code = "https://github.com/ovumcy/ovumcy-web"

[integration]
yunohost = ">= 12.1.40"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/ovumcy"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["en", "ru", "es", "fr", "de"]
    default = "en"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/ovumcy/ovumcy-web/archive/refs/tags/v1.3.0.tar.gz"
    sha256 = "7ce5f01404b30418f876c0530dfdd5b43b271261c195281043e9e23cb2590b57"

    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "24"

    [resources.go]
    version = "1.26.4"