#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "ovumcy"
name = "Ovumcy"
description.en = "A menstrual cycle tracker you run yourself. Your data stays on your server."

version = "1.4.0~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "AGPL-3.0"
website = "https://ovumcy.com/"
code = "https://github.com/ovumcy/ovumcy-web"

[integration]
yunohost = ">= 12.1.40"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "1500M"
ram.build = "1000M"
ram.runtime = "120M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "all_users"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["en", "ru", "es", "fr", "de"]
    default = "en"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/ovumcy/ovumcy-web/archive/refs/tags/v1.4.0.tar.gz"
    sha256 = "71e4ecd35637b7f9d1ef76d19478c5d819faa86ce3ddb177520d187fdf35524c"

    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "postgresql, postgresql-contrib"

    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "24"

    [resources.go]
    version = "1.26.4"